name: ci

on:
  push:
    branches:
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch Info
        id: branch_info
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: env RELEASE_TAG=${{ steps.branch_info.outputs.TAG }} make
      - name: Build Files
        run: ls ${{ github.workspace }}/bin
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/dist
          key: build-go-${{ hashFiles('**/*.sha256') }}
          restore-keys: |
            build-go-
